// Mocks generated by Mockito 5.0.17 from annotations
// in warehouse_flow/test/app/table/domain/usecase/find_warehouse_with_register_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:warehouse_flow/app/table/domain/entities/warehouse.dart' as _i6;
import 'package:warehouse_flow/app/table/domain/errors/table_exception.dart'
    as _i5;
import 'package:warehouse_flow/app/table/domain/repositories/warehouse_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [WarehouseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWarehouseRepository extends _i1.Mock
    implements _i3.WarehouseRepository {
  MockWarehouseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.TableException, _i6.Warehouse>>
      findWithRegisterById(int? id) => (super.noSuchMethod(
              Invocation.method(#findWithRegisterById, [id]),
              returnValue:
                  Future<_i2.Either<_i5.TableException, _i6.Warehouse>>.value(
                      _FakeEither_0<_i5.TableException, _i6.Warehouse>()))
          as _i4.Future<_i2.Either<_i5.TableException, _i6.Warehouse>>);
}
